url: https://log.pitchblackwallpaper.tecdrop.com

title: Pitch Black Wallpaper

theme: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

repository: tecdrop/log.pitchblackwallpaper
